### ISSUE TITLE
preloader is not loading in chrome,brave and edge

### ISSUE THREAD

**Issue by Aslin-R** [MCSMCOE/smcoe_webpage#12]

**Comment by roshan-lal-dia** [comment]
The problem with MP4 and Chromium-based browsers is that MP4 is a proprietary format that requires a license to use. [Chromium is an open-source project that does not include support for the proprietary H.264 video codec that is commonly used for MP4 and video streaming](https://support.vuplex.com/articles/how-to-enable-proprietary-video-codecs/)⁶. This means that Chromium cannot play MP4 videos natively, unless it is compiled with all codecs or uses a plugin to enable H.264 support⁹.

Some Chromium-based browsers, such as Google Chrome, Microsoft Edge, and Opera, include support for MP4 and H.264 by default, because they have obtained the necessary licenses or use their own implementations of the codec¹²⁵. However, other Chromium-based browsers, such as Vivaldi, Brave, and Comodo Dragon, do not support MP4 and H.264 by default, because they respect the open-source nature of Chromium and do not want to pay for the license or compromise the privacy of their users¹²³.

Therefore, if you want to play MP4 videos on a Chromium-based browser, you need to either use a browser that supports it by default, or install a plugin or extension that enables H.264 support for your browser. Alternatively, you can use a different format that is supported by all Chromium-based browsers, such as WebM or Ogg⁹¹².

**Comment by MCSMCOE** [comment]
#11 solved the issue
